### ISSUE TITLE
[BUG] System.IO.IOException:“设备未就绪。 : 'I:\'”

### ISSUE THREAD

**Issue by wifi-left** [DearVa/ExplorerEx#1]
System.IO.IOException:“设备未就绪。 : 'I:\'”
I:\ 是我的光驱，没有放光盘

**Comment by wifi-left** [comment]
```
if (useCache) {
				lock (CachedIcons) {
					CachedIcons.Add(extension, icon);
//System.ArgumentException:“An item with the same key has already been added. Key: .lnk”
				}
			}
```

**Comment by wifi-left** [comment]
这是另一个bug
然后还有双击文本容易进入编辑模式而不是进入目录

**Comment by DearVa** [comment]
> System.IO.IOException:“设备未就绪。 : 'I:'” I:\ 是我的光驱，没有放光盘

bug，麻烦提供对应的Log信息（位于软件目录下Logs文件夹中），我身边没有带光驱的电脑不好复现。



> ```
> if (useCache) {
> 				lock (CachedIcons) {
> 					CachedIcons.Add(extension, icon);
> //System.ArgumentException:“An item with the same key has already been added. Key: .lnk”
> 				}
> 			}
> ```

bug，lock没有完全覆盖关键段，暂时使用TryAdd来解决。



> 这是另一个bug 然后还有双击文本容易进入编辑模式而不是进入目录

bug，下一次提交修复。

**Comment by SeaIceNX** [comment]
> System.IO.IOException:“设备未就绪。 : 'I:'” I:\ 是我的光驱，没有放光盘

我分支给de了（

**Comment by DearVa** [comment]
> > System.IO.IOException:“设备未就绪。 : 'I:'” I:\ 是我的光驱，没有放光盘
> 
> 我分支给de了（

好家伙
