### ISSUE TITLE
建议别用.Net 6.0，因为很多电脑没有！！

### ISSUE THREAD

**Issue by TotoWang-hhh** [DearVa/ExplorerEx#10]
现在，我又得去下载了

真就几个世纪才能装好呗

**Comment by SeaIceNX** [comment]
？？？没有不能下吗
下载很快的啊

**Comment by TotoWang-hhh** [comment]
> ？？？没有不能下吗
> 
> 下载很快的啊

主要是之前版本的.NET给我留下了安装步骤繁琐的印象

**Comment by SeaIceNX** [comment]
> [doge]后续正式发布的时候我会发布多个版本的~（C# 10新语法真好用）

或许可以等NativeAOT完善直接打包成Native程序？

**Comment by DearVa** [comment]
这种不是issue的可以移步至discussion区哦

**Comment by DearVa** [comment]
> 

目前还没想法，AOT的话估计对插件支持就不好了，而且目前AOT好像还都不支持WPF

**Comment by DearVa** [comment]
> > [doge]后续正式发布的时候我会发布多个版本的~（C# 10新语法真好用）
> 
> 或许可以等NativeAOT完善直接打包成Native程序？

目前还没想法，AOT的话估计对插件支持就不好了，而且目前AOT好像还都不支持WPF

**Comment by TotoWang-hhh** [comment]
> [doge]后续正式发布的时候我会发布多个版本的~（C# 10新语法真好用）

手动狗头是吧（手动滑稽）
