### ISSUE TITLE
你先听我讲，这次真的是个BUG

### ISSUE THREAD

**Issue by TotoWang-hhh** [DearVa/ExplorerEx#14]
我的Win10电脑，终于装上环境打开了软件，可是基本上只要是涉及切换界面或者弹出什么东西的按钮，全都点不动，具体有下面这些：
- 快速访问
- 更多选项
- 设置

可能还有别的我没发现

**Comment by DearVa** [comment]
更多选项和设置还没做，只是摆了个按钮在那[doge]

**Comment by TotoWang-hhh** [comment]
> 更多选项和设置还没做，只是摆了个按钮在那[doge]

你是说这个没做？
![image](https://user-images.githubusercontent.com/67090055/159153981-beb36793-9c51-4b6f-87ba-3de94a83ab57.png)

**Comment by DearVa** [comment]
> > 更多选项和设置还没做，只是摆了个按钮在那[doge]
> 
> 你是说这个没做？ ![image](https://user-images.githubusercontent.com/67090055/159153981-beb36793-9c51-4b6f-87ba-3de94a83ab57.png)

没做，目前只是个傻按钮
