### ISSUE TITLE
Ctrl+双击 直接闪退

### ISSUE THREAD

**Issue by Yur1et** [DearVa/ExplorerEx#16]
不知道是不是我自己的问题，如果这种方式能快速分屏或者，打开新标签页就好了捏

**Comment by DearVa** [comment]
请问问题出现在哪个软件版本上呢？Release发布有延迟，有些bug可能在最新的commit中已被修复。我明天看看ctrl+双击的问题

**Comment by DearVa** [comment]
未复现，应该在新版本中被修复了。过两天等我把回收站做完我就发一个新的release
