### ISSUE TITLE
[功能建议]支持在路径栏中通过单击而跳转到相应路径

### ISSUE THREAD

**Issue by Achley-233** [DearVa/ExplorerEx#17]
请求支持在路径栏中可以通过单击而跳转到相应路径，就像Windows传统的文件资源管理器一样

https://user-images.githubusercontent.com/69111766/161167090-9e82bc45-1182-4a7b-98db-0fd820dfbb79.mp4

。
~在哔哩哔哩看到了大佬的项目很感兴趣，着急想试试但主力机没在身边只能先拿备用机来试。~
~没想到不仅可以在win7正常运行而且还挺好康（~

**Comment by DearVa** [comment]
搞定

**Comment by Achley-233** [comment]
好耶
