### ISSUE TITLE
It crashes when executing it

### ISSUE THREAD

**Issue by Andy312432** [DearVa/ExplorerEx#19]
Device : i5-9400F
Memory: 16GB
Operating System: Windows 11 21H2 x86
Runtime installed: Net 6.0 desktop

直接執行無反應
扔出一個LOG檔
或者是...安裝說明?
No replies when double-clicking it...
Returns a log file when using cmd..
Or... make a setup instruction...?

[2022-04-01.txt](https://github.com/DearVa/ExplorerEx/files/8399125/2022-04-01.txt)
.

**Comment by DearVa** [comment]
Please check out the latest commit [https://github.com/DearVa/ExplorerEx/commit/237485ffcc4d38d2b5e213ae7a0e4735e389b330](237485) if it fixed this problem.

**Comment by Andy312432** [comment]
一個簡單的問題
我如何Build他？

**Comment by DearVa** [comment]
最簡單的方式就是在[此處](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-windows-x64-installer)下載安裝.NET 6 SDK，之後在源代碼根目錄執行dotnet build -a x64 -c Release

**Comment by DearVa** [comment]
我在最新的commit中移除了對com組件的引用，您可以fork這個commit進行build。之前的版本直接使用dotnet build會出現錯誤（需要改用更麻煩的msbuild）

**Comment by Andy312432** [comment]
![image](https://user-images.githubusercontent.com/31586206/163721190-7e861679-2468-4052-8c56-093b2779429b.png)
現在他無法正確找到我的.NET了...

**Comment by DearVa** [comment]
這裡有一篇[文章](https://docs.microsoft.com/zh-cn/dotnet/core/tools/troubleshoot-usage-issues)提到：

> 如果将.NET SDK 安装到非默认位置，则需要将环境变量 DOTNET_ROOT 设置到包含 dotnet 可执行文件的目录。

**Comment by DearVa** [comment]
破案了，是Fody的鍋。下次我發佈一個帶有運行時的版本，應該會解決這個問題。
