### ISSUE TITLE
[BUG] 选盘符的界面切换图标显示大小会崩溃

### ISSUE THREAD

**Issue by Miuzarte** [DearVa/ExplorerEx#21]
![image](https://user-images.githubusercontent.com/66856838/161741459-e780a271-2471-40ac-ae38-90e72728af83.png)

**Comment by Gokr-ble** [comment]
遇到了同样的问题，但是在我的电脑上不会出现弹窗或创建Log日志，而是直接闪退；
系统：Win11 21H2，.NET 6.0

**Comment by DearVa** [comment]
最新的提交应该解决了这个问题
