### ISSUE TITLE
点击收藏夹内文件夹报错

### ISSUE THREAD

**Issue by unx123475** [DearVa/ExplorerEx#26]
我将download收藏进收藏夹，时而会报错，如下图，并且闪退。时而没问题，可以正常运
![error](https://user-images.githubusercontent.com/60565965/163274242-a7841b28-132b-4656-bcf2-6a9680df5aed.png)
行

**Comment by DearVa** [comment]
感谢反馈，我会尽快修复。（这一段在忙比赛可能要拖更一段时间QAQ）

**Comment by unx123475** [comment]
不急，慢慢来

**Comment by DearVa** [comment]
好久没出现这个问题了，可能解决了吧
