### ISSUE TITLE
[BUG] 选盘符的界面选择“查看”-“内容”时不显示任何东西

### ISSUE THREAD

**Issue by Miuzarte** [DearVa/ExplorerEx#27]
![image](https://user-images.githubusercontent.com/66856838/163674759-7359eb1b-054b-43a6-acad-da18de95768f.png)

**Comment by Miuzarte** [comment]
以及更改之后不会记忆，第二次打开仍会回复默认的“详细信息”

**Comment by DearVa** [comment]
“内容”我还没做[doge]所以看不到

**Comment by DearVa** [comment]
> 以及更改之后不会记忆，第二次打开仍会恢复为默认的“详细信息”

这是bug，我去修一下

**Comment by Miuzarte** [comment]
设置里关闭最后一个标签页时我选择了回到首页
此时用ctrl+w关闭最后一个标签页的时候会一片空白

**Comment by Miuzarte** [comment]
还有就是左下角那个齿轮按钮没反应，也没做么（

**Comment by DearVa** [comment]
> 还有就是左下角那个齿轮按钮没反应，也没做么（

没做😂

**Comment by DearVa** [comment]
> 还有就是左下角那个齿轮按钮没反应，也没做么（

设置界面我打算做成流畅设计，过几天把样式先写了再说
