### ISSUE TITLE
[BUG]在“此电脑”中查看属性，不会打开“此电脑”的属性，而是会打开ExplorerEx安装目录的属性

### ISSUE THREAD

**Issue by TotoWang-hhh** [DearVa/ExplorerEx#29]
如题

**Comment by DearVa** [comment]
感谢反馈，我会尽快修复。（这一段比较忙要鸽一段QAQ）

**Comment by DearVa** [comment]
已修复[cadb5cb](https://github.com/DearVa/ExplorerEx/commit/cadb5cbf619059f81b81861e455d8295700230aa)
