### ISSUE TITLE
[BUG]右键菜单的鼠标悬浮效果没了！？

### ISSUE THREAD

**Issue by TotoWang-hhh** [DearVa/ExplorerEx#30]
如题
以前的α测版本里，鼠标在右键菜单上移动会有一个菜单被按压倾斜的效果，现在Win10亲测没了……
但愿只是个BUG。千万别删掉这个细节效果，那是我做喜欢的东西了

**Comment by DearVa** [comment]
很不幸，该特性已经移除，因为很容易误操作（特别是弹出了子集菜单之后），而且这样的菜单无法应用云母或者亚克力效果。

**Comment by TotoWang-hhh** [comment]
> 很不幸，该特性已经移除，因为很容易误操作（特别是弹出了子集菜单之后），而且这样的菜单无法应用云母或者亚克力效果。

那，针对Win10把菜单圆角削没了这个怎么解释？

**Comment by DearVa** [comment]
> > 很不幸，该特性已经移除，因为很容易误操作（特别是弹出了子集菜单之后），而且这样的菜单无法应用云母或者亚克力效果。
> 
> 那，针对Win10把菜单圆角削没了这个怎么解释？

圆角是win11的特性，我只是调用了对应的API，所以win10不支持圆角。
