### ISSUE TITLE
[BUG]插入被BitLocker锁定U盘导致ExplorerEx卡死

### ISSUE THREAD

**Issue by TotoWang-hhh** [DearVa/ExplorerEx#31]
如题
截图：
![image](https://user-images.githubusercontent.com/67090055/164175067-41d808ec-e0d4-47eb-ac61-e8d0c41d26f7.png)

**Comment by DearVa** [comment]
目前尚不支持bitlocker

**Comment by TotoWang-hhh** [comment]
> 目前尚不支持bitlocker

很不幸，它把我下载的ExplorerEx副本整废了，现在已经启动不了了……打开已经没反应了……

**Comment by DearVa** [comment]
> > 目前尚不支持bitlocker
> 
> 很不幸，它把我下载的ExplorerEx副本整废了，现在已经启动不了了……打开已经没反应了……

您可以尝试使用[这个工具](https://github.com/DearVa/ExplorerEx/releases/tag/debug)，然后把生成的dump文件发给我。

**Comment by TotoWang-hhh** [comment]
> > > 目前尚不支持bitlocker
> > 
> > 
> > 很不幸，它把我下载的ExplorerEx副本整废了，现在已经启动不了了……打开已经没反应了……
> 
> 您可以尝试使用[这个工具](https://github.com/DearVa/ExplorerEx/releases/tag/debug)，然后把生成的dump文件发给我。

我觉得，你可以在后面的版本里内置这玩意呢，单独下载好麻烦

**Comment by TotoWang-hhh** [comment]
> > > 目前尚不支持bitlocker
> > 
> > 
> > 很不幸，它把我下载的ExplorerEx副本整废了，现在已经启动不了了……打开已经没反应了……
> 
> 您可以尝试使用[这个工具](https://github.com/DearVa/ExplorerEx/releases/tag/debug)，然后把生成的dump文件发给我。

这样又跑起来了
![image](https://user-images.githubusercontent.com/67090055/164177276-1c544f21-cf42-4d80-a6c6-e84c936ac978.png)

**Comment by DearVa** [comment]
> > > > 目前尚不支持bitlocker
> > > 
> > > 
> > > 很不幸，它把我下载的ExplorerEx副本整废了，现在已经启动不了了……打开已经没反应了……
> > 
> > 
> > 您可以尝试使用[这个工具](https://github.com/DearVa/ExplorerEx/releases/tag/debug)，然后把生成的dump文件发给我。
> 
> 这样又跑起来了 ![image](https://user-images.githubusercontent.com/67090055/164177276-1c544f21-cf42-4d80-a6c6-e84c936ac978.png)

可以插上U盘，等崩溃之后会生成一个dmp文件

**Comment by TotoWang-hhh** [comment]
> > > > > 目前尚不支持bitlocker
> > > > 
> > > > 
> > > > 很不幸，它把我下载的ExplorerEx副本整废了，现在已经启动不了了……打开已经没反应了……
> > > 
> > > 
> > > 您可以尝试使用[这个工具](https://github.com/DearVa/ExplorerEx/releases/tag/debug)，然后把生成的dump文件发给我。
> > 
> > 
> > 这样又跑起来了 ![image](https://user-images.githubusercontent.com/67090055/164177276-1c544f21-cf42-4d80-a6c6-e84c936ac978.png)
> 
> 可以插上U盘，等崩溃之后会生成一个dmp文件

《迟 迟 不 崩 溃 的 顽 强 的 软 件》

**Comment by DearVa** [comment]
草，多点点叉看它蚌埠蚌。

**Comment by TotoWang-hhh** [comment]
++，白等了！！
闪退了，但是没有dmp文件
输出信息没来得及截图就自己没了

**Comment by DearVa** [comment]
看看logs文件夹呢，有没有输出

**Comment by TotoWang-hhh** [comment]
您就自己看看您会觉得在哪里吧
![image](https://user-images.githubusercontent.com/67090055/164179141-4721e2ca-9fe5-41b0-a07a-d2a166665f46.png)

**Comment by TotoWang-hhh** [comment]
稍等一下，我写一个简单的Python程序来保存输出信息

**Comment by DearVa** [comment]
在`RunWithDumpWatcher.bat`中加一个`-h`参数试试看。即`ExplorerEx.exe | procdump64 -e -t -h ExplorerEx.exe`

**Comment by TotoWang-hhh** [comment]
## 输出信息截图
有输出信息的截图了
![image](https://user-images.githubusercontent.com/67090055/164180444-7a0f79ce-3b67-4e38-944b-91855bf03ba1.png)

## 猜测
目测是无法获取卷标

## 建议
只要是获取不成功就别尝试了，在卷标那里写“无法识别”。这样至少可以防止卡死，至于BitLocker的支持可以以后慢慢做。

## DMP文件
至于DMP文件，现在还是没有。

## 其他分析
从输出信息的速度和内容的一致性来看，程序到后来似乎陷入了死循环，说不定就是太久没刷新界面，挂起太久，被系统封kill掉的。

---
*以上纯属本人猜想

**Comment by DearVa** [comment]
已修复
