### ISSUE TITLE
菜单栏->查看点击大图标、小图标问题

### ISSUE THREAD

**Issue by aowon** [DearVa/ExplorerEx#32]
使用环境：WIN11，软件运行时提示.NET环境，下载的.NET版本为windowsdesktop-runtime-6.0.4-win-x64
问题：
1、大图标切换点击小图标后文件图标未能正确缩放。
![image](https://user-images.githubusercontent.com/49396047/164418850-56f2355b-ad4a-45f7-a324-eb345106c263.png)
2、点击大图标后，对号位置不会切换，仍然显示在小图标文本前面。
![image](https://user-images.githubusercontent.com/49396047/164419428-9fc01c45-9828-426b-852e-f70f59d7d480.png)
3、点击左下方的设置图标没有反应。
建议：深色模式下的图标和字体看的不是很清晰，应该是图标颜色有点淡，期待图标的船新版本。
![image](https://user-images.githubusercontent.com/49396047/164420613-69127b22-1951-47fd-9202-73a3339b8d83.png)

**Comment by aowon** [comment]
看到之前的issue，好像设置只是一个图标。

**Comment by DearVa** [comment]
已在[4607a20](https://github.com/DearVa/ExplorerEx/commit/4607a2081e383ef7d5e6a93ac96030d2ddd7b983)中修复，感谢您的贡献
