### ISSUE TITLE
[Bug/New Feature]希望添加地址栏环境变量快捷跳转

### ISSUE THREAD

**Issue by Gokr-ble** [DearVa/ExplorerEx#35]
目前版本在地址栏中输入环境变量（如%userprofile%，%appdata%等）会提示“#InvalidPath”，且顶部标签页左侧会不停转圈圈，下方页面空白，如视频所示：

https://user-images.githubusercontent.com/44522297/179404354-8dc31a10-f0cb-4666-933d-d58278c9d0d7.mp4

：
感谢感谢~

**Comment by DearVa** [comment]
感谢您的建议，我会在下个版本中添加此功能。

**Comment by DearVa** [comment]
已在[216272f](https://github.com/DearVa/ExplorerEx/commit/216272f4db72c38a3dca882e867d27e02366f73e)中添加该功能。
