### ISSUE TITLE
[Feature Request]支持在文件夹内通过按下数字、字母等按键快速定位文件

### ISSUE THREAD

**Issue by RCUTANF** [DearVa/ExplorerEx#39]
在Windows的文件资源管理器中，只要焦点存在于当前目录的窗口，就可以通过按下指定的字符对应定位以该字符开头的文件。例如，按下字母A快速定位所有以A开头的文件。并且Windows的资源管理器支持通过连续按下按键在所有以该字符开头的文件中切换。 除此之外，对于非数字和英文的字符也是支持的。例如在输入法开启的情况下用输入法输好“我”字并向窗口发送，可以定位以“我”字开头的文件。

另外夹带私货夸一句😁，这个项目非常不错，我会尽己所能大力支持！！

**Comment by DearVa** [comment]
wakuwaku！感谢支持~这就安排！

**Comment by DearVa** [comment]
做好了！[@177e9f](https://github.com/DearVa/ExplorerEx/commit/177e9f38ac9de38a6cedd59b923a7c8d902a123b)
