### ISSUE TITLE
[bug]由操作文件时产生的一系列视觉问题

### ISSUE THREAD

**Issue by RCUTANF** [DearVa/ExplorerEx#40]
在新建、粘贴文件或文件夹的时候，软件窗口中会显示2个完全相同的文件或文件夹{like this:
![image](https://user-images.githubusercontent.com/110910565/183689742-960a4d4e-3d74-4396-bde8-a7b23527be9e.png)
![image](https://user-images.githubusercontent.com/110910565/183689793-8008ee2a-04d9-40ed-9da5-bc765b2cf1de.png)
然后。去查看了一下文件目录，发现这个只是视觉上的错误，实际并没有创建、粘贴2个相同的文件夹。然后在软件中退出这个目录，重新再进入这个目录时，显示会恢复正常。我在复数台设备上测试，此bug均存在；但没有在复数种系统上测试，可能是Windows11特性。
补充一下图一中的神奇的地方：图一中显示的创建日期并不相同，是因为一个是我把文件复制过来之前文件原始的创建日期，另一个是文件复制时的日期。

**Comment by RCUTANF** [comment]
> 这是个很老的bug了，我一直没有着手去修复。如果可能的话，请附上详细的复现步骤，我会尽快解决，不胜感激。 Message ID: ***@***.***&gt;

https://user-images.githubusercontent.com/110910565/183782897-f9f881e0-41c1-473c-b37e-fcff1d0c1167.mp4


https://user-images.githubusercontent.com/110910565/183784156-66a6ac7d-eb91-4e03-95a3-1e9647f8c0e7.mp4


这2个视频可以把问题完全的展现出来。当然可能没什么帮助。如果需要的话，可以指导我进入调试模式来导出详细的日志。

**Comment by RCUTANF** [comment]
视频中还顺带出现了几处bug：删除文件窗口的‘关闭’控件无法按下，右键菜单缺少粘贴控件，隐藏文件没有隐藏的视觉效果，剪切文件时没有视觉效果反馈，自定义文件（夹）图标不显示

**Comment by DearVa** [comment]
新增设置是否显示隐藏文件，并添加了对应的视觉效果。
