### ISSUE TITLE
BHO插件要如何使用？

### ISSUE THREAD

**Issue by sunshe35** [DearVa/ExplorerEx#42]
电脑win10 专业版21H2.

我现在导航到任意目录，按Enter键弹出的还是默认浏览器。
使用浏览器打开文件所在文件夹，弹出的还是默认浏览器。
所以这个BHO插件要如何使用呢？需要自己编译吗？

此外，在这个窗口下listary无效（指输入关键字搜索无效）。

**Comment by DearVa** [comment]
在ExplorerEx设置最底部，勾选“设置为默认”

**Comment by sunshe35** [comment]
找不到这个设置，甚至都没找到设置选项。只有右下角有三个按钮，还不可以选择。

**Comment by DearVa** [comment]
请使用Actions中的最新版：[下载链接](https://github.com/DearVa/ExplorerEx/suites/8132657423/artifacts/352447497)

**Comment by sunshe35** [comment]
谢谢老哥恢复。

替换原来程序之后，左下角的设置出来了。然后设置bho依然没有成功。放弃了。
这个在全屏状态下，无法最小化。窗口状态下可以最小化。

**Comment by DearVa** [comment]
请问设置的过程中有报错或者任何提示吗

**Comment by DearVa** [comment]
您可尝试安装.NET Framework 4.6.2之后再次尝试 [下载链接](https://download.visualstudio.microsoft.com/download/pr/8e396c75-4d0d-41d3-aea8-848babc2736a/80b431456d8866ebe053eb8b81a168b3/ndp462-kb3151800-x86-x64-allos-enu.exe)

**Comment by sunshe35** [comment]
安装失败，我的计算机已经安装了4.6.2或更高版本的更新。

**Comment by DearVa** [comment]
您可以检查一下注册表是否存在`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Browser Helper Objects\{11451400-8700-480c-a27f-000001919810}`项

**Comment by sunshe35** [comment]
有的，刚看了下。SetExplorerExProxy.reg文件里面的内容都生效了。但是这个项里面没有数值。

**Comment by DearVa** [comment]
没有数值是正常的，只要有这个项，Windows文件管理器启动时就会尝试加载CLSID中对应的拓展，位于`Computer\HKEY_CLASSES_ROOT\CLSID\{11451400-8700-480C-A27F-000001919810}`。

**Comment by sunshe35** [comment]
懂了，谢谢老哥指点。

**Comment by DearVa** [comment]
如果这些都有但是没有生效，那重启一下资源管理器或者电脑试试吧））

**Comment by sunshe35** [comment]
找到原因了，是你把SetExplorerExProxy.reg文件里的CodeBase路径写死了。要自己修改才行。

**Comment by DearVa** [comment]
唔……在设置中修改的话，ExplorerEx会自动替换那个路径的

**Comment by sunshe35** [comment]
ok，确实是这样。
可能是我操作失误，最后一步没有点击确定。

**Comment by DearVa** [comment]
原来如此，我去优化一下交互方式。

**Comment by DearVa** [comment]
我把对话框个数减到了只有一个，我之前之所以放了很多对话框是因为担心它不够安全，但是我今天下午测试过了，即便BHO的dll被删除也不会影响Windows Explorer的正常运作。相比Files直接修改注册表的方式更加安全，而且也不会报毒。

**Comment by DearVa** [comment]
但是这个BHO插件基于.NET Framework 4.6.2，我尚不清楚他在win7系统上是否可以正常运作。
接下来我会尝试用C++重写BHO来使其脱离Runtime。
