### ISSUE TITLE
右键选择编辑文件，如果目录中含有空格会显示找不到文件

### ISSUE THREAD

**Issue by Luke-Corden** [DearVa/ExplorerEx#51]
https://user-images.githubusercontent.com/102634834/203699151-c23d5934-6993-4a61-a550-b439a5e44d8b.mp4

**Comment by 1031507008** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
