### ISSUE TITLE
考虑背景铺满整个窗口不

### ISSUE THREAD

**Issue by zhaotianff** [DearVa/ExplorerEx#62]
加个开关，背景铺满整个窗口这样。

![image](https://github.com/DearVa/ExplorerEx/assets/22126367/d654e2ef-ad86-4ac4-8a51-e6b9d438232a)

![image](https://github.com/DearVa/ExplorerEx/assets/22126367/214941ce-a1bd-4fd4-bd2c-895a8890f62a)

**Comment by DearVa** [comment]
可能要对整个视觉树进行较大的改动才能实现

**Comment by zhaotianff** [comment]
是的，确实得做一些不小的改动。😃
