### ISSUE TITLE
我似乎看见了什么……

### ISSUE THREAD

**Issue by TotoWang-hhh** [DearVa/ExplorerEx#9]
好耶！恭喜你们有第一个Release了！
不过给我看见了就是（手动滑稽）
我下载了，去体验一下

**Comment by DearVa** [comment]
感谢支持~目前该项目主要由我一个人开发，所以进度会比较缓慢。

**Comment by DearVa** [comment]
如果十分感兴趣不妨点个Watch，这样子有更新会提醒哦

**Comment by TotoWang-hhh** [comment]
我把Release的通知打开了，就守着这里了（我基本上每天看邮箱）
